### ISSUE TITLE
Render todo lists

### ISSUE THREAD

**Issue by ronantuantvt2** [truongquangloi/react-todo#3]
- [x] Create todo state
- [x] Load toto state to list
- [x] Handle add new todo
- [x] Update todo list
- [x] Delete todo
